dateModified: 1791372361
meta:
  __names__:
    0f7dbd20-f39e-57db-8b25-dcadccdd1733: Craft # Craft
    1a1f4c85-de86-4c34-9fb1-f6c0bba5304a: Pages # Pages
    4b27d877-0924-47cc-8a6f-b2a591a7f796: 'Public Schema' # Public Schema
    7bfe9119-221f-4a6f-b450-86b1f81fb4cb: Asset # Asset
    8a11481b-da87-47ae-9626-e572ab131c0e: Default # Default
    68bcc1ae-e3c4-486f-8d76-e6db3fe1a93f: 'Knecht Works' # Knecht Works
    76f4bb16-621b-47e6-a47b-b42a0741bdf4: Richtext # Richtext
    7480c632-a5a8-4f7c-9f8e-fc97c2b1365d: EN # EN
    086104d4-cbc2-4ac3-aba8-706b10fb7576: Images # Images
    a26b11c0-da8e-418d-8a51-fc5d4411134c: 'Plain Text' # Plain Text
    b2dc6ff6-cb1f-4eec-8be3-e974fb8b99be: Home # Home
    dee56a08-c55c-4108-a4af-fea2b06d9dd0: DE # DE
    e2b05374-8ac3-4487-a137-e43cc30ddd9a: GB # GB
    e7a19cdd-1559-4d99-baf1-63812a369060: 'Richtext Large' # Richtext Large
system:
  edition: pro
  name: 'Knecht Works'
  schemaVersion: 6.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
