handle: richtext
instructions: null
name: Richtext
searchable: false
settings:
  assetSelectionCondition:
    __assoc__:
      -
        - elementType
        - CraftCms\Cms\Asset\Elements\Asset
      -
        - fieldContext
        - global
      -
        - forQuery
        - false
      -
        - class
        - CraftCms\Cms\Asset\Conditions\AssetCondition
      -
        - conditionRules
        - __assoc__:
            -
              - operator
              - and
            -
              - rules
              -
                - __assoc__:
                    -
                      - class
                      - CraftCms\Cms\Asset\Conditions\ViewableConditionRule
                    -
                      - uid
                      - 7f92b5a2-3b36-4ae9-84c4-d3bd03109107
                    -
                      - value
                      - true
  availableVolumes: '*'
  byteLimit: null
  charLimit: null
  encode: false
  flavor: gfm
  htmlSanitizer: null
  initialRows: 8
  inlineOnly: false
  linkSettingsShowLabelField: false
  linkSettingsTypes:
    - entry
    - url
  placeholder: null
  sanitizeHtml: true
  showStats: false
  showToolbar: true
  showUnpermittedVolumes: false
  toolbarButtons:
    - bold
    - italic
    - strikethrough
    - code
    - h1
    - h2
    - h3
    - quote
    - unordered-list
    - ordered-list
    - check-list
    - link
    - asset
    - preview
    - guide
  uploadVolume: null
translationKeyFormat: null
translationMethod: site
type: CraftCms\Cms\Field\Markdown
